# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 19)),
        ),
    ]
