# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
