# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=1000)),
                ('late_work_policy', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('two_parents', models.BooleanField(default=False)),
                ('parent1_name', models.CharField(max_length=50)),
                ('parent2_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(default='01/01/2000')),
                ('student_phone', models.CharField(max_length=20)),
                ('parent1_phone', models.CharField(max_length=20)),
                ('parent2_phone', models.CharField(max_length=20)),
                ('parent1_email', models.EmailField(max_length=254)),
                ('parent2_email', models.EmailField(max_length=254)),
                ('student_email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=50)),
                ('school_website', models.URLField()),
                ('school_calendar', models.URLField()),
                ('grades_account', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='student.Teacher'),
        ),
        migrations.AddField(
            model_name='contacted',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
