# Generated by Django 2.0.6 on 2019-05-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180726_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.PositiveIntegerField(default='917253'),
        ),
    ]
